version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/irisdev/app/merge.cpf
    command: 
      --check-caps false
    ports: 
      - 1972
      - 53795:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - ./init.db/:/docker-entrypoint-initdb.d/

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    hostname: 'zookeeper'
    ports:
      - 2181:2181
    environment:
      - 'ZOOKEEPER_CLIENT_PORT=2181'
      - 'ZOOKEEPER_TICK_TIME=2000'
      - 'JMX_PORT=9999'

    restart: 'on-failure'

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-manager:
    image: 'eduard93/kafka-manager-demo:latest'
    hostname: 'kafka-manager'
    depends_on:
      - 'kafka'
    environment:
      - 'KAFKA_SERVERS_URL=kafka:9092'
    ports:
      - 8082:8082
    restart: 'on-failure'